spring:
  cloud:
    consul:
      host: ${CONSUL_URL}
      port: ${CONSUL_PORT}
      discovery:
        instance-id: ${TDX_INSTANCE_ID}
        ip-address: ${EXPOSE_IP}
        prefer-ip-address: true
        service-name: spring-srest
  application:
    name: consul-demo
  datasource:
    url: ${MYSQL_URL}
    driver-class-name:com.mysql.jdbc.Driver
server:
  port: ${EXPOSE_PORT}
mybatis:
  type-aliases-package: mybatis.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

