spring:
  cloud:
    consul:
      host: ${CONSUL_URL}
      port: ${CONSUL_PORT}
      discovery:
        instance-id: ${TDX_INSTANCE_ID}
        ip-address: ${EXPOSE_IP}
        prefer-ip-address: true
        service-name: spring-srest
  application:
    name: consul-demo
server:
  port: ${EXPOSE_PORT}
