CREATE TABLE IF NOT EXISTS `SKV`(
   `SKEY` VARCHAR(100) NOT NULL,
   `SVALUE` VARCHAR(100) NOT NULL,
   PRIMARY KEY ( `SKEY` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `SUSER`(
   `uid` INT UNSIGNED AUTO_INCREMENT,
)