
Author: Tsual
#debug: true
---
#redis
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db0?user=root&password=123456&charset=Unicode&serverTimezone=GMT
    username: root
    password: zli5314584
    driver-class-name: com.mysql.cj.jdbc.Driver