/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sf_jni_HalloJni */

#ifndef _Included_sf_jni_HalloJni
#define _Included_sf_jni_HalloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sf_jni_HalloJni
 * Method:    foo
 * Signature: ([BLjava/lang/String;ILjava/lang/Object;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sf_jni_HalloJni_foo
  (JNIEnv *, jclass, jbyteArray, jstring, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
